spring:
  application:
    name: activity-service
  mongodb:
    host: localhost
    port: 27017
    database: fitness_activity_db
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8082